# Generated by Django 4.2.2 on 2023-11-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionales',
            name='Tarifa',
            field=models.IntegerField(default=25000, null=True, verbose_name='Tarifa por hora del profesional'),
        ),
    ]
