# Generated by Django 4.2.2 on 2023-10-24 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='Estado',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='FechaAtencion',
            field=models.DateField(null=True, verbose_name='Fecha de atención'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='FechaHoraSolicitud',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='IdBloque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloque', to='app.bloque', verbose_name='ID de bloque'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='IdBox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_box', to='app.box'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='IdContrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_contrato', to='app.contrato'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='RutPaciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='app.pacientes', verbose_name='Rut del paciente'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='RutProfesional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to='app.profesionales', verbose_name='Rut del profesional'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='Tarifa',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
