# Generated by Django 4.2.6 on 2023-10-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_agenda_estado_alter_agenda_fechaatencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='Cell',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de celular del paciente'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='Direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección del paciente'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico del paciente'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='Estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado del paciente'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='FechaNac',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento del paciente'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro del paciente'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='NombreSocial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre social del paciente'),
        ),
    ]
