# Generated by Django 4.2.2 on 2023-11-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bloque_rutprofesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='Tarifa',
            field=models.DecimalField(decimal_places=2, default=25000, max_digits=10, null=True),
        ),
    ]
