# Generated by Django 4.2.2 on 2023-11-16 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_box_idagenda_box_idusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='IdUsuario',
        ),
        migrations.AddField(
            model_name='box',
            name='IdAgenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_box', to='app.agenda'),
        ),
    ]
