# Generated by Django 4.2.2 on 2023-11-16 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_box_idusuario_box_idagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='IdAgenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_box', to='app.agenda'),
        ),
    ]
