# Generated by Django 4.2.2 on 2023-11-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_box_idagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='Tarifa',
            field=models.IntegerField(default=25000, null=True),
        ),
    ]
