# Generated by Django 4.2.2 on 2023-11-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_agenda_tarifa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='IdAgenda',
        ),
        migrations.AddField(
            model_name='box',
            name='Estado',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
